#!/usr/bin/env bash
# script that transfers a file from our client to a server

# Assigning arguments to variables
path_to_file="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_to_file" "$username"@"$server_ip":~/
fi
