#!/usr/bin/env bash
# This script configures Nginx server so that /redirect_me
# must be a “301 Moved Permanently”

# Install nginx server
sudo apt-get install -y nginx

# Create a basic index.html file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html

# Define string for replacement in nginx configuration
str_replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.elouardy.com permanent;"

# Replace the default server_name with the defined string in nginx configuration
sudo sed -i "s/server_name _;/$str_replace/" /etc/nginx/sites-enabled/default

# Restart nginx service to apply changes
sudo service nginx restart

