#!/usr/bin/env bash
# This script configures the Nginx server to have a custom 404 page

# Install nginx server
sudo apt-get install -y nginx

# Create a basic index.html file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html

# Define string for replacement in nginx configuration
str_replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.elouardy.com permanent;"

# Replace the default server_name with the defined string in nginx configuration
sudo sed -i "s/server_name _;/$str_replace/" /etc/nginx/sites-enabled/default

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Add to the default nginx configuration
replace_str="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$replace_str/" /etc/nginx/sites-enabled/default


# Restart nginx service to apply changes
sudo service nginx restart
