#!/usr/bin/env bash
# displays the contents of the file "/etc/passwd"
# only displays the username, user id, and home directory path of the user

myfile="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d":" -f1,3,6
done < "$myfile"
