#!/usr/bin/env bash
# groups visitors by IP and HTTP status code, and displays this data.
# Requirements:
# The exact format must be:
    # OCCURENCE_NUMBER IP HTTP_CODE
    # In list format
# Ordered from the greatest to the lowest number of occurrences

myfile="apache-access.log"
awk -F' ' '{ print $1, $9}' $myfile | sort | uniq -c|sort -nr
