#!/usr/bin/env bash
# fixes a web server to run Nginx as the nginx user
# on port 8080

# set a user in the config by replace '#user' and it's value
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# replace port 80 with 8080 in the sites-available config
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# grant the owner the permission to read and write the config file
chmod 644 /etc/nginx/nginx.conf
# kill apache process if it is running to avoid interfere with nginx
pkill apache2
# now start the nginx service with the new nginx user
sudo -u nginx service nginx start
